### ISSUE TITLE
Local install using NPM not working

### ISSUE THREAD

**Issue by ojizero** [dawson-org/dawson-cli#209]
When installing Dawson locally using NPM, it can't run deployment of the code, exits with the following error.

```
dawson internal error: spawn /Users/oji/Workspace/Work/lambdas/mono/dawson-framework/node_modules/dawson/node_modules/.bin/babel ENOENT
Error: spawn /Users/oji/Workspace/Work/lambdas/mono/dawson-framework/node_modules/dawson/node_modules/.bin/babel ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

---

After tracing the error in the code, I suspect the error is caused by the code returning the child process of Babel in the first trial using the babelPath that works with the Global or Yarn installed module, specifically [this line](https://github.com/dawson-org/dawson-cli/blob/master/src/libs/language-javascript-latest/compile.js#L15).

Since `execa` returns a promise, and nothing waits on it, causing the code to return before the catch block is catches the `ENOENT` error.

---

Node version: `v8.9.4`
NPM version: `5.6.0`
OS: `macOS 10.13.2`

**Comment by ojizero** [comment]
@aguyinmontreal so sorry for the late response, I suspect the fix for this would be to `await` when running `execa` in [this line](https://github.com/dawson-org/dawson-cli/blob/master/src/libs/language-javascript-latest/compile.js#L15), but I'm not 100% sure nor did I test it honestly as I was only testing Dawson, and ended up using Apex since it fit our needs better.
