### ISSUE TITLE
Updating support stack failed

### ISSUE THREAD

**Issue by lcasartelli** [dawson-org/dawson-cli#73]
_Updating support stack_ task failed with error:

```bash
An error occurred while deploying
{ ValidationError: Stack with id mywebsiteSupport does not exist
    at Request.extractError (/home/luca/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/home/luca/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/luca/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/luca/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/home/luca/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/luca/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/luca/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/luca/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/luca/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/home/luca/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Stack with id mywebsiteSupport does not exist',
  code: 'ValidationError',
  time: 2016-12-01T09:19:48.347Z,
  requestId: '4e54cb11-b7a7-11e6-ad0b-073671dfed3c',
  statusCode: 400,
  retryable: false,
  retryDelay: 32.47982731777217,
  context:
   { cloudfrontSettings: 'mywebsite.com',
     dangerDeleteResources: false,
     defs:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     hostedZoneId: null,
     skip: false,
     stackName: 'mywebsiteProd',
     stageName: 'prod',
     appStage: 'prod',
     supportStackName: 'mywebsiteSupport' } }
```

**.env-prod**
```bash
export AWS_PROFILE=mywebsiteprofile
export AWS_REGION=eu-west-1
export DAWSON_STAGE=prod
export NODE_ENV=prod
```

**Comment by lusentis** [comment]
There was a bug that prevented stacks in regions other than `us-east-1` to be correctly updated. The update did fail as in your case. This issue is now fixed in v5.0.0 (release notes coming soon)
