### ISSUE TITLE
Not restarting when lambda error occurs

### ISSUE THREAD

**Issue by azappa** [dawson-org/dawson-cli#81]
Got this when lambda throws error and dawson won't watch / restart.

```
Lambda terminated with error:
 { errorMessage: '{"unhandled":true,"message":"Unhandled internal error","httpStatus":500}' } 
Unhandled Error: Your lambda function returned an invalid error. Error messages must be valid JSON.stringfy-ed strings and should contain an httpStatus (int) property. This error will be swallowed and a generic HTTP 500 response will be returned to the client. Please refer to the documentation for instruction on how to deliver proper error responses. 
TypeError: First argument must be a string or Buffer
    at ServerResponse.write (_http_outgoing.js:460:11)
    at apiCallback (/home/alessio/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/src/commands/proxy.js:144:13)
    at doCall (/home/alessio/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/src/commands/proxy.js:217:7)
    at _callee$ (/home/alessio/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/src/commands/proxy.js:224:5)
    at tryCatch (/home/alessio/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/alessio/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/regenerator-runtime/runtime.js:337:22)
    at Generator.prototype.(anonymous function) [as next] (/home/alessio/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/regenerator-runtime/runtime.js:96:21)
    at step (/home/alessio/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/alessio/.nvm/versions/node/v7.1.0/lib/node_modules/dawson/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by lusentis** [comment]
fixed in 2cc38ab, will ship with the next release
