### ISSUE TITLE
Error with dawson describe

### ISSUE THREAD

**Issue by azappa** [dawson-org/dawson-cli#99]
The command outputs this:
```
Command error TypeError: Cannot read property 'toString' of undefined
    at /home/alessio/repos/dawson-cli-original/node_modules/cli-table/lib/index.js:182:26
    at Array.forEach (native)
    at generateRow (/home/alessio/repos/dawson-cli-original/node_modules/cli-table/lib/index.js:181:11)
    at /home/alessio/repos/dawson-cli-original/node_modules/cli-table/lib/index.js:275:16
    at Table.forEach (native)
    at Table.toString (/home/alessio/repos/dawson-cli-original/node_modules/cli-table/lib/index.js:258:10)
    at Promise.all.then (../../src/commands/describe.js:57:7)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7) 
```

**Comment by lusentis** [comment]
Thanks for the report, if you're using the git version, this is fixed in the env-vars branch.
